name: Build Ramayana Database

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-db:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"


    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Build SQLite Database
      run: |
        python build_ramayana_db.py


    - name: Upload Database
      uses: actions/upload-artifact@v4
      with:
        name: ramayana-database
        path: ramayana.db

    - name: Test API
  run: |
    python test_api.py
